import bcrypt from "bcryptjs";

const allData = {
  users: [
    {
      // id: 1,
      name: "John Doe",
      email: "aadmin@example.com",
      password: bcrypt.hashSync("A123456", 10),
      isAdmin: true,
    },

    {
      // id: 2,
      name: "John Doe",
      email: "vitech@example.com",
      password: bcrypt.hashSync("B123456", 10),
      isAdmin: false,
    },
  ],

  logo: [
    {
      id: 1,
      name: "blessed redeemer fashion and design",
      img: "/logo/logo1.jpg",
    },
  ],

  hero: [
    {
      id: 1,
      name: "blessed redeemer fashion and design",
      img: "/img/pic2.jpg",
    },

    {
      id: 2,
      name: "blessed redeemer fashion and design",
      img: "/img/pic3.jpg",
    },

    {
      id: 3,
      name: "blessed redeemer fashion and design",
      img: "/img/pic4.jpg",
    },

    {
      id: 4,
      name: "blessed redeemer fashion and design",
      img: "/img/pic5.jpg",
    },

    {
      id: 5,
      name: "blessed redeemer fashion and design",
      img: "/img/pic7.jpg",
    },

    {
      id: 6,
      name: "blessed redeemer fashion and design",
      img: "/img/pic8.jpg",
    },
  ],

  homeCategory: {
    women: [
      {
        id: 1,
        name: "women",
        slug: "longsleev",
        img: "/img/pic2.jpg",
      },
    ],

    men: [
      {
        id: 1,
        name: "men",
        slug: "longsleev",
        img: "/img/pic3.jpg",
      },
    ],

    kids: [
      {
        id: 1,
        name: "kids",
        slug: "longsleev",
        img: "/img/pic4.jpg",
      },
    ],

    unisex: [
      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic7.jpg",
      },
    ],

    shirts: [
      {
        id: 1,
        name: "shirts",
        slug: "longsleev",
        img: "/img/pic7.jpg",
      },
    ],
  },

  // Banner
  banner: {
    womenBanner: [
      {
        id: 1,
        name: "women",
        slug: "longsleev",
        img: "/img/pic11.jpg",
      },

      {
        id: 1,
        name: "women",
        slug: "longsleev",
        img: "/img/pic12.jpg",
      },

      {
        id: 1,
        name: "women",
        slug: "longsleev",
        img: "/img/pic13.jpg",
      },

      {
        id: 1,
        name: "women",
        slug: "longsleev",
        img: "/img/pic14.jpg",
      },
    ],

    featBanner: [
      {
        id: 1,
        name: "men",
        slug: "longsleev",
        img: "/img/pic16.jpg",
      },
    ],

    kidsBanner: [
      {
        id: 1,
        name: "kids",
        slug: "longsleev",
        img: "/img/pic17.jpg",
      },

      {
        id: 1,
        name: "kids",
        slug: "longsleev",
        img: "/img/pic18.jpg",
      },

      {
        id: 1,
        name: "kids",
        slug: "longsleev",
        img: "/img/pic19.jpg",
      },

      {
        id: 1,
        name: "kids",
        slug: "longsleev",
        img: "/img/pic10.jpg",
      },
    ],

    unisex: [
      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic21.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic22.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic23.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic5.jpg",
      },
    ],

    menBanner: [
      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic7.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic9.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic10.jpg",
      },

      {
        id: 1,
        name: "unisex",
        slug: "longsleev",
        img: "/img/pic11.jpg",
      },
    ],
  },

  // Featured Products
  featuredProducts: [
    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic2.jpg",
      price: 50,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
      banner: "/img/pic5.jpg",
    },

    {
      name: "short Sleev",
      slug: "shortsleev",
      category: "Sleeves",
      image: "/img/pic3.jpg",
      price: 25.0,
      brand: "African Print",
      countInStock: 0,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 6,
      isFeatured: true,
      banner: "/img/pic5.jpg",
    },

    {
      name: "long shirt",
      slug: "longshirt",
      category: "Sleeves",
      image: "/img/pic4.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "short shirt",
      slug: "shortshirt",
      category: "Sleeves",
      image: "/img/pic5.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 3,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "nothern fugu",
      slug: "nothernfugu",
      category: "Sleeves",
      image: "/img/pic7.jpg",
      price: 15.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "southern fugu",
      slug: "southernfugu",
      category: "Sleeves",
      image: "/img/pic8.jpg",
      price: 44.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "afican kente",
      slug: "africankente",
      category: "Sleeves",
      image: "/img/pic9.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.4,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "chiffon",
      slug: "chiffon",
      category: "Sleeves",
      image: "/img/pic10.jpg",
      price: 150.0,
      brand: "African Print",
      countInStock: 4,
      rating: 4.6,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic11.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 6,
      rating: 3.9,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "maxi dress",
      slug: "maxidress",
      category: "Sleeves",
      image: "/img/pic12.jpg",
      price: 13.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "off shoulder",
      slug: "offshoulder",
      category: "Sleeves",
      image: "/img/pic13.jpg",
      price: 100.0,
      brand: "African Print",
      countInStock: 20,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
    },
  ],

  // New Products
  NewProducts: [
    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic2.jpg",
      price: 50,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
      banner: "/img/pic5.jpg",
    },

    {
      name: "short Sleev",
      slug: "shortsleev",
      category: "Sleeves",
      image: "/img/pic3.jpg",
      price: 25.0,
      brand: "African Print",
      countInStock: 0,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 6,
      isFeatured: true,
      banner: "/img/pic5.jpg",
    },

    {
      name: "long shirt",
      slug: "longshirt",
      category: "Sleeves",
      image: "/img/pic4.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "short shirt",
      slug: "shortshirt",
      category: "Sleeves",
      image: "/img/pic5.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 3,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "nothern fugu",
      slug: "nothernfugu",
      category: "Sleeves",
      image: "/img/pic7.jpg",
      price: 15.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "southern fugu",
      slug: "southernfugu",
      category: "Sleeves",
      image: "/img/pic8.jpg",
      price: 44.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "afican kente",
      slug: "africankente",
      category: "Sleeves",
      image: "/img/pic9.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.4,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "chiffon",
      slug: "chiffon",
      category: "Sleeves",
      image: "/img/pic10.jpg",
      price: 150.0,
      brand: "African Print",
      countInStock: 4,
      rating: 4.6,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic11.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 6,
      rating: 3.9,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "maxi dress",
      slug: "maxidress",
      category: "Sleeves",
      image: "/img/pic12.jpg",
      price: 13.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "off shoulder",
      slug: "offshoulder",
      category: "Sleeves",
      image: "/img/pic13.jpg",
      price: 100.0,
      brand: "African Print",
      countInStock: 20,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
    },
  ],

  // Shirts
  homeShirt: [
    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic2.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
      // banner: "/img/pic5.jpg",
    },

    {
      name: "short Sleev",
      slug: "shortsleev",
      category: "Sleeves",
      image: "/img/pic3.jpg",
      price: 25.0,
      brand: "African Print",
      countInStock: 0,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 6,
      isFeatured: true,
      // banner: "/img/pic5.jpg",
    },

    {
      name: "long shirt",
      slug: "longshirt",
      category: "Sleeves",
      image: "/img/pic4.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "short shirt",
      slug: "shortshirt",
      category: "Sleeves",
      image: "/img/pic5.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 3,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "nothern fugu",
      slug: "nothernfugu",
      category: "Sleeves",
      image: "/img/pic7.jpg",
      price: 15.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "southern fugu",
      slug: "southernfugu",
      category: "Sleeves",
      image: "/img/pic8.jpg",
      price: 44.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "afican kente",
      slug: "africankente",
      category: "Sleeves",
      image: "/img/pic9.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.4,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "chiffon",
      slug: "chiffon",
      category: "Sleeves",
      image: "/img/pic10.jpg",
      price: 150.0,
      brand: "African Print",
      countInStock: 4,
      rating: 4.6,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic11.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 6,
      rating: 3.9,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "maxi dress",
      slug: "maxidress",
      category: "Sleeves",
      image: "/img/pic12.jpg",
      price: 13.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "off shoulder",
      slug: "offshoulder",
      category: "Sleeves",
      image: "/img/pic13.jpg",
      price: 100.0,
      brand: "African Print",
      countInStock: 20,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
    },
  ],

  // Trousers
  trousers: [
    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic10.jpg",
      price: 50,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
      // banner: "/img/pic5.jpg",
    },

    {
      name: "short Sleev",
      slug: "shortsleev",
      category: "Sleeves",
      image: "/img/pic11.jpg",
      price: 25.0,
      brand: "African Print",
      countInStock: 0,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 6,
      isFeatured: true,
      // banner: "/img/pic5.jpg",
    },

    {
      name: "long shirt",
      slug: "longshirt",
      category: "Sleeves",
      image: "/img/pic13.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "short shirt",
      slug: "shortshirt",
      category: "Sleeves",
      image: "/img/pic20.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 3,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "nothern fugu",
      slug: "nothernfugu",
      category: "Sleeves",
      image: "/img/pic16.jpg",
      price: 15.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "southern fugu",
      slug: "southernfugu",
      category: "Sleeves",
      image: "/img/pic18.jpg",
      price: 44.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "afican kente",
      slug: "africankente",
      category: "Sleeves",
      image: "/img/pic19.jpg",
      price: 50.0,
      brand: "African Print",
      countInStock: 0,
      rating: 4.4,
      description: "high quality African ware",
      numReviews: 7,
      isFeatured: true,
    },

    {
      name: "chiffon",
      slug: "chiffon",
      category: "Sleeves",
      image: "/img/pic20.jpg",
      price: 150.0,
      brand: "African Print",
      countInStock: 4,
      rating: 4.6,
      description: "high quality African ware",
      numReviews: 9,
      isFeatured: true,
    },

    {
      name: "Long Sleev",
      slug: "longsleev",
      category: "Sleeves",
      image: "/img/pic21.jpg",
      price: 10.0,
      brand: "African Print",
      countInStock: 6,
      rating: 3.9,
      description: "high quality African ware",
      numReviews: 8,
      isFeatured: true,
    },

    {
      name: "maxi dress",
      slug: "maxidress",
      category: "Sleeves",
      image: "/img/pic22.jpg",
      price: 13.0,
      brand: "African Print",
      countInStock: 5,
      rating: 3.5,
      description: "high quality African ware",
      numReviews: 5,
      isFeatured: true,
    },

    {
      name: "off shoulder",
      slug: "offshoulder",
      category: "Sleeves",
      image: "/img/pic23.jpg",
      price: 100.0,
      brand: "African Print",
      countInStock: 20,
      rating: 4.5,
      description: "high quality African ware",
      numReviews: 10,
      isFeatured: true,
    },
  ],
};
export default allData;

// Categories
export const allCategories = [
  {
    name: "Women",
    slug: "women",
    products: [
      {
        name: "Long Sleeves",
        slug: "tops",
        category: "Sleeves",
        image: "/img/pic2.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Smog",
        slug: "shortSmog",
        category: "Sleeves",
        image: "/img/pic3.jpg",
        price: 25.0,
        brand: "African Print",
        countInStock: 0,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 6,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Afro Shirt",
        slug: "afro-shirt",
        category: "Sleeves",
        image: "/img/pic4.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 8,
        isFeatured: true,
      },
      {
        name: "Wax Print",
        slug: "wax-print",
        category: "Sleeves",
        image: "/img/pic5.jpg",
        price: 10.0,
        brand: "African Print",
        countInStock: 3,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Northern Fugu",
        slug: "northern-fugu",
        category: "Sleeves",
        image: "/img/pic7.jpg",
        price: 15.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Southern Fugu",
        slug: "southern-fugu",
        category: "Sleeves",
        image: "/img/pic8.jpg",
        price: 44.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "African Kente",
        slug: "african-kente",
        category: "Sleeves",
        image: "/img/pic9.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.4,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Chiffon",
        slug: "chiffon",
        category: "Sleeves",
        image: "/img/pic10.jpg",
        price: 150.0,
        brand: "African Print",
        countInStock: 4,
        rating: 4.6,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Maxi Dress",
        slug: "maxi-dress",
        category: "Sleeves",
        image: "/img/pic12.jpg",
        price: 13.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Off Shoulder",
        slug: "off-shoulder",
        category: "Sleeves",
        image: "/img/pic13.jpg",
        price: 100.0,
        brand: "African Print",
        countInStock: 20,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
      },
    ],
  },

  // men
  {
    name: "Men",
    slug: "men",
    products: [
      {
        name: "Kente",
        slug: "kente",
        category: "Sleeves",
        image: "/img/pic2.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Luxury",
        slug: "luxury",
        category: "Sleeves",
        image: "/img/pic3.jpg",
        price: 25.0,
        brand: "African Print",
        countInStock: 0,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 6,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Modern",
        slug: "modern",
        category: "Sleeves",
        image: "/img/pic4.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 8,
        isFeatured: true,
      },
      {
        name: "Original",
        slug: "original",
        category: "Sleeves",
        image: "/img/pic5.jpg",
        price: 10.0,
        brand: "African Print",
        countInStock: 3,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "High Quality",
        slug: "high-quality",
        category: "Sleeves",
        image: "/img/pic7.jpg",
        price: 15.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Scarf",
        slug: "scarf",
        category: "Sleeves",
        image: "/img/pic8.jpg",
        price: 44.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Jacket",
        slug: "jacket",
        category: "Sleeves",
        image: "/img/pic9.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.4,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Formal",
        slug: "formal",
        category: "Sleeves",
        image: "/img/pic10.jpg",
        price: 150.0,
        brand: "African Print",
        countInStock: 4,
        rating: 4.6,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Native",
        slug: "native",
        category: "Sleeves",
        image: "/img/pic12.jpg",
        price: 13.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Off Shoulder",
        slug: "men-off-shoulder",
        category: "Sleeves",
        image: "/img/pic13.jpg",
        price: 100.0,
        brand: "African Print",
        countInStock: 20,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
      },
    ],
  },

  // kids
  {
    name: "Kids",
    slug: "kids",
    products: [
      {
        name: "Kid Long Sleeves",
        slug: "kids-long-sleeves",
        category: "Sleeves",
        image: "/img/pic2.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Kids Short Sleeves",
        slug: "kids-short-sleeves",
        category: "Sleeves",
        image: "/img/pic3.jpg",
        price: 25.0,
        brand: "African Print",
        countInStock: 0,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 6,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Kids Long Shirt",
        slug: "kids-long-shirt",
        category: "Sleeves",
        image: "/img/pic4.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 8,
        isFeatured: true,
      },
      {
        name: "Kids-Short Shirt",
        slug: "kids-short-shirt",
        category: "Sleeves",
        image: "/img/pic5.jpg",
        price: 10.0,
        brand: "African Print",
        countInStock: 3,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Kids Northern Fugu",
        slug: "kids-northern-fugu",
        category: "Sleeves",
        image: "/img/pic7.jpg",
        price: 15.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Kids Southern Fugu",
        slug: "kids-southern-fugu",
        category: "Sleeves",
        image: "/img/pic8.jpg",
        price: 44.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Kids African Kente",
        slug: "kids-african-kente",
        category: "Sleeves",
        image: "/img/pic9.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.4,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Kids Chiffon",
        slug: "kids-chiffon",
        category: "Sleeves",
        image: "/img/pic10.jpg",
        price: 150.0,
        brand: "African Print",
        countInStock: 4,
        rating: 4.6,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Kids Maxi Dress",
        slug: "kids-maxi-dress",
        category: "Sleeves",
        image: "/img/pic12.jpg",
        price: 13.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Kids Off Shoulder",
        slug: "kids-off-shoulder",
        category: "Sleeves",
        image: "/img/pic13.jpg",
        price: 100.0,
        brand: "African Print",
        countInStock: 20,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
      },
    ],
  },

  // unisex
  {
    name: "Unisex",
    slug: "unisex",
    products: [
      {
        name: "Unisex Long Sleeves",
        slug: "unisex-long-sleeves",
        category: "Sleeves",
        image: "/img/pic2.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Unisex Short Sleeves",
        slug: "unisex-short-sleeves",
        category: "Sleeves",
        image: "/img/pic3.jpg",
        price: 25.0,
        brand: "African Print",
        countInStock: 0,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 6,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Unisex Long Shirt",
        slug: "unisex-long-shirt",
        category: "Sleeves",
        image: "/img/pic4.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 8,
        isFeatured: true,
      },
      {
        name: "Unisex Short Shirt",
        slug: "unisex-short-shirt",
        category: "Sleeves",
        image: "/img/pic5.jpg",
        price: 10.0,
        brand: "African Print",
        countInStock: 3,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Unisex Northern Fugu",
        slug: "unisex-northern-fugu",
        category: "Sleeves",
        image: "/img/pic7.jpg",
        price: 15.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Unisex Southern Fugu",
        slug: "unisex-southern-fugu",
        category: "Sleeves",
        image: "/img/pic8.jpg",
        price: 44.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Unisex African Kente",
        slug: "unisex-african-kente",
        category: "Sleeves",
        image: "/img/pic9.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.4,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Unisex Chiffon",
        slug: "unisex-chiffon",
        category: "Sleeves",
        image: "/img/pic10.jpg",
        price: 150.0,
        brand: "African Print",
        countInStock: 4,
        rating: 4.6,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Unisex Maxi Dress",
        slug: "unisex-maxi-dress",
        category: "Sleeves",
        image: "/img/pic12.jpg",
        price: 13.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Unisex Off Shoulder",
        slug: "unisex-off-shoulder",
        category: "Sleeves",
        image: "/img/pic13.jpg",
        price: 100.0,
        brand: "African Print",
        countInStock: 20,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
      },
    ],
  },

  // Shirts
  {
    name: "Shirts",
    slug: "shirt",
    products: [
      {
        name: "Shirt Long Sleeves",
        slug: "shirt-tops",
        category: "Sleeves",
        image: "/img/pic2.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "shirt-Smog",
        slug: "shirt-short-Smog",
        category: "Sleeves",
        image: "/img/pic3.jpg",
        price: 25.0,
        brand: "African Print",
        countInStock: 0,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 6,
        isFeatured: true,
        // banner: "/img/pic5.jpg",
      },
      {
        name: "Afro Shirt",
        slug: "afro-shirt",
        category: "Sleeves",
        image: "/img/pic4.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 8,
        isFeatured: true,
      },
      {
        name: "Wax Print",
        slug: "wax-print",
        category: "Sleeves",
        image: "/img/pic5.jpg",
        price: 10.0,
        brand: "African Print",
        countInStock: 3,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Northern Fugu",
        slug: "northern-fugu",
        category: "Sleeves",
        image: "/img/pic7.jpg",
        price: 15.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Southern Fugu",
        slug: "southern-fugu",
        category: "Sleeves",
        image: "/img/pic8.jpg",
        price: 44.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "African Kente",
        slug: "african-kente",
        category: "Sleeves",
        image: "/img/pic9.jpg",
        price: 50.0,
        brand: "African Print",
        countInStock: 0,
        rating: 4.4,
        description: "High quality African wear",
        numReviews: 7,
        isFeatured: true,
      },
      {
        name: "Chiffon",
        slug: "chiffon",
        category: "Sleeves",
        image: "/img/pic10.jpg",
        price: 150.0,
        brand: "African Print",
        countInStock: 4,
        rating: 4.6,
        description: "High quality African wear",
        numReviews: 9,
        isFeatured: true,
      },
      {
        name: "Maxi Dress",
        slug: "maxi-dress",
        category: "Sleeves",
        image: "/img/pic12.jpg",
        price: 13.0,
        brand: "African Print",
        countInStock: 5,
        rating: 3.5,
        description: "High quality African wear",
        numReviews: 5,
        isFeatured: true,
      },
      {
        name: "Off Shoulder",
        slug: "off-shoulder",
        category: "Sleeves",
        image: "/img/pic13.jpg",
        price: 100.0,
        brand: "African Print",
        countInStock: 20,
        rating: 4.5,
        description: "High quality African wear",
        numReviews: 10,
        isFeatured: true,
      },
    ],
  },
];
